spring.application.name=Pfe
server.port=8080

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/stardb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger
springdoc.api-docs.path=/v3/api-docs


#JWT
app.jwt.secret=HkoRZD25/yNejM0H4dw2t46GZilXV784+E6sMbBdM4I=
app.jwt.expiration-ms=86400000
